name: C CI

# xxx could be written as:  "on: [push, pull_request]"
on:
  push:
    branches: [ bsdmake ]
  pull_request:
    branches: [ bsdmake ]

jobs:
  regressionTest:
    name: "${{ matrix.os }} ${{ matrix.cc }} ${{ matrix.make }} ${{ matrix.sanitizer }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04, ubuntu-latest, macOS-11.0, macOS-latest ] # netbsd!!!
        cc: [ gcc, clang ]
        make: [ bmake, pmake, make ]
        sanitizer: [ NO_SANI, USE_ASAN, USE_UBSAN, USE_LEAKSAN ]
        exclude:
        - os: [ macOS-11.0, macOS-latest ]
          # it's clang anyway
          cc: gcc
          # pmake is unavailable, make is gmake
          make: [ pmake, make ]
        - os: [ ubuntu-18.04, ubuntu-latest ]
          # it's gmake
          make: make

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: dependencies (Ubuntu)
      if: matrix.os == 'ubuntu'
      run: |
        uname -a
        sudo apt-get install pmake bmake cxref
        ${{ matrix.cc }} --version
    - name: dependencies (MacOS-11.0)
      if: matrix.os == 'macOS-11.0'
      run: |
        uname -a
        brew install bmake cxref
        ${{ matrix.cc }} --version
    - name: dependencies (MacOS-latest)
      if: matrix.os == 'macOS-latest'
      run: |
        uname -a
        brew install bmake cxref
        ${{ matrix.cc }} --version
    - name: dependencies (NetBSD-latest)
      if: matrix.os == 'netbsd-latest'
      run: |
        uname -a
        pkgin install cxref clang
        ${{ matrix.cc }} --version
    - name: builddir
      run: rm -rf build && mkdir build
    - name: build
      run: MAKEOBJDIRPREFIX=$(pwd)/build ${{ matrix.make }} -j 3 CC=${{ matrix.cc }} ${{ matrix.sanitizer }}=yes
    - name: distribution
      run: MAKEOBJDIRPREFIX=$(pwd)/build DESTDIR=$(pwd)/dist ${{ matrix.make }} -j 3 install
    - name: regression
      run: MAKEOBJDIRPREFIX=$(pwd)/build ${{ matrix.make }} regress ${{ matrix.sanitizer }}=yes
